name: mapper
description: Library converts map to object and object to map. Can use external converters for custom complex types. 
version: 0.2.1
homepage: https://github.com/0xff00ff/mapper

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: 1.5.0
