name: mapper
description: Library converts map to object and object to map. Can use external converters for custom complex types. 
version: 0.1.3
homepage: https://github.com/0xff00ff/mapper
author: 0xff00ff <0xff00ff@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: 1.5.0
